[toolchain]
solana-version = "2.2.20"
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
chumchon = "CVjwSHMQ9YTenzKwQczwXWzJFk5kwaUhKDtxDKVazJXj"

[programs.devnet]
chumchon = "CVjwSHMQ9YTenzKwQczwXWzJFk5kwaUhKDtxDKVazJXj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mx/chumchon-app/deploy-keypair.json"
docker = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"